# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('wounds', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('faction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transport_capacity', models.IntegerField(default=0)),
                ('move', models.IntegerField(default=0)),
                ('ws', models.IntegerField(default=0)),
                ('bs', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('wounds', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('ws', models.IntegerField(default=0)),
                ('bs', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('wounds', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='species',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.PlanetType'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='previous_accounts',
            field=models.ManyToManyField(blank=True, to='app.Account'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Species'),
        ),
        migrations.AddField(
            model_name='account',
            name='characters',
            field=models.ManyToManyField(blank=True, to='app.Character'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
