# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='faction',
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ManyToManyField(blank=True, to='app.Faction'),
        ),
    ]
