# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161030_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_capacity', models.IntegerField(default=0)),
                ('move', models.IntegerField(default=0)),
                ('ws', models.IntegerField(default=0)),
                ('bs', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('wounds', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='armor',
            new_name='armor_mod',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='bs',
            new_name='bs_mod',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='move',
            new_name='move_mod',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='transport_capacity',
            new_name='transport_capacity_mod',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='wounds',
            new_name='wounds_mod',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='ws',
            new_name='ws_mod',
        ),
        migrations.AddField(
            model_name='ship',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ShipTemplate'),
        ),
    ]
